CREATE TABLE IF NOT EXISTS users (
    id BIGSERIAL PRIMARY KEY
    , name VARCHAR(100) NOT NULL
    , email VARCHAR(100) NOT NULL UNIQUE
    , password VARCHAR(100) NOT NULL
    , online BOOLEAN NOT NULL DEFAULT FALSE
    , active BOOLEAN NOT NULL DEFAULT TRUE
    , avatar TEXT NULL
    , created_by BIGINT NOT NULL
    , created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
    , updated_by BIGINT NULL
    , updated_at TIMESTAMP WITH TIME ZONE NULL
)